config/routes.rb
Rails.application.routes.draw do

  resources :twites do
    post '/comments', to: "comments#create", as: "comments"
    patch '/comments/:comment_id', to: "comments#update"
    delete '/comments/:comment_id', to: "comments#destroy"
    get '/comments/:comment_id', to: "comments#show"
  end

  devise_for :users
  root to: "twites#index"
  resources :users, except: [:index]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :twite
  has_one_attached :comment_picture
  # i expect [file, files] or file
end

app/models/twite.rb
class Twite < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many_attached :twite_pictures
  validates :twite_pictures, length: {maximum: 9}
  # , message: "goober" }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :twites
  has_many :comments
  has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!

    before_action :check_user_profile, except: [:edit, :update, :destroy, :create]

    def check_user_profile
        # render plain: current_user.inspect
        if user_signed_in?
            if !current_user.name || !current_user.address || !current_user.display_name
                redirect_to edit_user_path(current_user)
            end
        end
    end

    def after_sign_in_path_for(resource)
        # return new_user_path
        if !current_user.name || !current_user.address || !current_user.display_name
            return edit_user_path(current_user)
        else
            return root_path 
        end
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :get_comment, only: [:destroy] #,:show]

  def create
    @comment = Comment.new(comment_params)
    @comment.twite_id = params[:twite_id]
    @comment.user_id = current_user.id
    @comment.comment_picture.attach(params[:comment][:comment_picture])
    @comment.save
    redirect_to twite_path(params[:twite_id])
  end

  def show
    # Fixed this easy
    @comments = Comment.where(twite_id: params[:twite_id])
    @comment = @comments[params[:comment_id].to_i - 1]
  end

  def update
  end

  def destroy
    # @comment = Comment.find(params[:comment_id]) #=> now in get_comment
    @comment.delete
    redirect_to "/twites/#{params[:twite_id]}"
  end

  private
  def comment_params
    params.require(:comment).permit(:body)
  end

  def get_comment
    @comment = Comment.find(params[:comment_id])
  end
end

app/controllers/twites_controller.rb
class TwitesController < ApplicationController
  before_action :set_twite, only: [:show, :edit, :update, :destroy]
  before_action :check_for_image_or_body, only: [:update, :create]

  def check_for_image_or_body
    if params[:twite][:body] == "" and params[:twite][:twite_picture] == nil
      render plain: "gotta have something \n Glen had body == nil when it should of been \n body == \"\" "
    end
  end

  # GET /twites
  # GET /twites.json
  def index
    @twites = Twite.all
  end

  # GET /twites/1
  # GET /twites/1.json
  def show
  end

  # GET /twites/new
  def new
    @twite = Twite.new
    # post /twites/
  end

  # GET /twites/1/edit
  def edit
    # @twite = Twite.find(params[:id])
    # patch /twites/params[:id]/
    if @twite.user_id != current_user.id
      redirect_to root_path, notice: "You can't do that you sneaky hacker boi!"
    end
  end

  # POST /twites
  # POST /twites.json
  def create
    @twite = Twite.new(twite_params)
    @twite.user_id = current_user.id
    @twite.twite_pictures.attach(params[:twite][:twite_pictures])
    
    respond_to do |format|
      if @twite.save
        format.html { redirect_to @twite, notice: 'Twite was successfully created.' }
        format.json { render :show, status: :created, location: @twite }
      else
        format.html { render :new }
        format.json { render json: @twite.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /twites/1
  # PATCH/PUT /twites/1.json
  def update
    @twite.twite_pictures.attach(params[:twite][:twite_pictures])
    respond_to do |format|
      if @twite.update(twite_params)
        format.html { redirect_to @twite, notice: 'Twite was successfully updated.' }
        format.json { render :show, status: :ok, location: @twite }
      else
        format.html { render :edit }
        format.json { render json: @twite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /twites/1
  # DELETE /twites/1.json
  def destroy
    @twite.destroy
    respond_to do |format|
      format.html { redirect_to twites_url, notice: 'Twite was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_twite
      @twite = Twite.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def twite_params
      params.require(:twite).permit(:body)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]


  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.find(current_user.id)
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    # @user = User.find()

    respond_to do |format|
      if @user.save
        format.html { redirect_to new_user_path, notice: 'Please create a profile.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    @user.avatar.attach(params[:user][:avatar])
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to root_path, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:display_name, :name, :address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/twites_helper.rb
module TwitesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/show.html.erb
<h2>View A Comment</h2>
<p><%= @comment.body %></p>
<p>Belongs To:<%= @comment.user.id %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <aside id="column-left">
    <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>

    </aside>
    <div id="column-middle">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
    <aside id="column-right">Sidebar2</aside>
  </body>
</html>

app/views/twites/_form.html.erb
<%= form_with(model: twite, local: true) do |form| %>
  <% if twite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(twite.errors.count, "error") %> prohibited this twite from being saved:</h2>

      <ul>
        <% twite.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_field :body %>
  </div>

  <div class="field">
    <%= form.label :twite_pictures %>
    <%= form.file_field :twite_pictures, multiple: true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/twites/edit.html.erb
<h1>Editing Twite</h1>

<%= render 'form', twite: @twite %>

<%= link_to 'Show', @twite %> |
<%= link_to 'Back', twites_path %>

app/views/twites/index.html.erb
<h1>Twites</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @twites.each do |twite| %>
      <tr>
        <td><%= twite.body %></td>
        <td><%= twite.user_id %></td>
        <td><%= link_to 'Show', twite %></td>
        <% if current_user.id == twite.user_id %>
          <td><%= link_to 'Edit', edit_twite_path(twite) %></td>
          <td><%= link_to 'Destroy', twite, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Twite', new_twite_path %>

app/views/twites/new.html.erb
<h1>New Twite</h1>

<%= render 'form', twite: @twite %>

<%= link_to 'Back', twites_path %>

app/views/twites/show.html.erb
<p>
  <strong>Body:</strong>
  <%= @twite.body %>
</p>

<% @twite.twite_pictures.each do |picture| %>
  <%= image_tag picture, width: "100", height: "100" %>
<% end %>

<p>
  <strong>User:</strong>
  <%= @twite.user_id %>
</p>

<% if current_user.id == @twite.user_id %>
  <%= link_to 'Edit', edit_twite_path(@twite) %> |
<% end %>
<%= link_to 'Back', twites_path %>

<h2>Filthy Comments Section</h2>
<% @twite.comments.each do |comment| %>
  <p><%= comment.body %></p>
  <%= image_tag(comment.comment_picture, width: "75", height: "75") if comment.comment_picture.attached? %>
  <% if current_user.id == comment.user_id || current_user.id == @twite.user_id %>
    <%= link_to "Delete", "/twites/#{@twite.id}/comments/#{comment.id}", method: :delete  %>
  <% end %>
<% end %>


<%= form_with(model: Comment.new, local: true, url: "/twites/#{@twite.id}/comments") do |form| %>
  <div>
    <%= form.label :body %>
    <%= form.text_field :body %>
  </div>
  <div>
    <%= form.label :comment_picture %>
    <%= form.file_field :comment_picture%>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :display_name %>
    <%= form.text_field :display_name %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div>
    <%= form.label :avatar %>
    <%= form.file_field :avatar %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>My Profile</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/new.html.erb
<h1>My Profile</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p>
  <strong>Display name:</strong>
  <%= @user.display_name %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @user.address %>
</p>

<%= image_tag(@user.avatar, height: "50", width: "50") if @user.avatar.attached? %> 

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>